### ISSUE TITLE
unable to find an inherited method for function ‘NSBS’ for signature ‘"standardGeneric"’

### ISSUE THREAD

**Issue by pangxueyu233** [GreenleafLab/10x-scATAC-2019#1]
Hello, 
It's really an awsome wroking. But I got a error by using your workflow in 01_Filter_Cells_v2, as following: 
> fragments <- fragments[mcols(fragments)[,by] %in% rownames(tssSingles)[tssSingles$cellCall==1]]
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘NSBS’ for signature ‘"standardGeneric"’

I don't know the _### mcols(fragments)[,by_] meaning, and I got error in this formula. 
Hope you could help me out.

Thanks

**Comment by pangxueyu233** [comment]
And I tried to change the code like this: 

fragments <- fragments[mcols(fragments)[,"RG"] %in% rownames(tssSingles)[tssSingles$cellCall==1]]

And it works, 
I know this step wants to filter cells but I'm not sure whether it's right by my fixing.

**Comment by pangxueyu233** [comment]
One more suggestion, could you upgrade the codes? Because some parts was used Seurat V2.3, it's not friendly to further people using seurat V3.
Thanks

**Comment by jeffmgranja** [comment]
looks like a variable got deleted

by = "RG"

i normally write it as mcols(fragments)$RG but i corrected it everywhere to be more flexible
