### ISSUE TITLE
Plot CNA

### ISSUE THREAD

**Issue by ccruizm** [GreenleafLab/10x-scATAC-2019#12]
Good day!

I am currently using ArchR. Great package! However, there is no implementation of CNA there (maybe in the future?). I have generated the cnaObj based on the code you shared. However, I am not sure how to plot the results. Could you please share how to do it and generate a nice figure like the one in your publication?

Thanks in advance!

**Comment by jefferyUstc** [comment]
hi, here, i'd like to ask what's the exact meaning of `RG` in the CNV analysis code?
